services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=flashcards
    volumes:
      - '.docker:/docker-entrypoint-initdb.d'
